### ISSUE TITLE
Syntax Error when using commonjs require

### ISSUE THREAD

**Issue by lfarrel6** [willsoto/casbin-objection-adapter#2]
I'm currently seeing an issue when requiring this module in Node 12.16.1. 

Using `require` seems to be resolving to the esm file which causes a syntax error due to the presence of import statements (`SyntaxError: Cannot use import statement outside a module`)

This issue may be due to the exports value in the package.json pointing to esm.js. One solution may be to use [conditional exports.](https://nodejs.org/api/esm.html#esm_conditional_exports)

**Comment by willsoto** [comment]
Sorry! I never got notified about this issue. I’ll look into it, thanks for the report.

**Comment by willsoto** [comment]
@lfarrel6 released as [v0.2.1](https://github.com/willsoto/casbin-objection-adapter/releases/tag/v0.2.1). Please let me know if this fixes the issue for you
